Add job to return submission errors to buildkite
This commit adds a script, `report_error.sh`, which is ran when
`schedule_job.sh` errors. It takes a job id and the error as arguments,
and it passes the error to buildkite, which checks if it exists and reports it.

Co-authored-by: nefrathenrici <nat.henrici@gmail.com>

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -17,6 +17,13 @@ export CI_BUILD_DIR="${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/${BUILDK
 export JULIA_DEPOT_PATH="${JULIA_DEPOT_PATH:-$CI_BUILD_DIR/depot/default}"
 export BUILDKITE_BUILD_CHECKOUT_PATH="${CI_BUILD_DIR}/${BUILDKITE_PIPELINE_SLUG}"
 
+# Report error if it exists
+if [ ! -z "${BUILDKITE_AGENT_META_DATA_ERROR+x}" ]; then
+    echo "--- Job submission error"
+    echo "error message: ${BUILDKITE_AGENT_META_DATA_ERROR}"
+    exit 1
+fi
+
 # Slurm Job Info
 
 if [ "$BUILDKITE_AGENT_META_DATA_QUEUE" != "derecho" ]; then
