Set up buildkite on Derecho, add set-up guide

diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -11,44 +11,43 @@
 set -euo pipefail # exit on failure or unset variable
 #set -x  # show all the commands that are being executed
 
-source /etc/profile.d/modules.sh
-
 export SLURM_BUILDKITE_PATH="$(dirname "${BUILDKITE_BIN_PATH}")"
 export GIT_SSH_COMMAND="ssh -i ${SLURM_BUILDKITE_PATH}/.ssh/id_rsa -o IdentitiesOnly=yes"
-export SHARED_DEPOT="${BUILDKITE_BUILD_PATH}/shared_depot"
 export CI_BUILD_DIR="${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/${BUILDKITE_BUILD_NUMBER}"
 export JULIA_DEPOT_PATH="${JULIA_DEPOT_PATH:-$CI_BUILD_DIR/depot/default}"
 export BUILDKITE_BUILD_CHECKOUT_PATH="${CI_BUILD_DIR}/${BUILDKITE_PIPELINE_SLUG}"
-export BUILDKITE_API_TOKEN=$(cat "${SLURM_BUILDKITE_PATH}/.buildkite_token")
 
 # Slurm Job Info
-echo "--- Slurm Job ID: ${SLURM_JOB_ID}"
-scontrol show job ${SLURM_JOB_ID} --details
-scontrol show node ${SLURM_JOB_NODELIST}
 
-export TMPDIR="/tmp/slurm-${SLURM_JOB_ID}"
+if [ "$BUILDKITE_AGENT_META_DATA_QUEUE" != "derecho" ]; then
+    source /etc/profile.d/modules.sh
+    echo "--- Slurm Job ID: ${SLURM_JOB_ID}"
+    scontrol show job ${SLURM_JOB_ID} --details
+    scontrol show node ${SLURM_JOB_NODELIST}
+
+    export TMPDIR="/tmp/slurm-${SLURM_JOB_ID}"
+else
+    echo "--- PBS Job ID: ${PBS_JOBID}"
+    qstat -f ${PBS_JOBID} || {
+        echo "Error: qstat failed" >&2
+    }
+    echo "Current nodes: $(cat $PBS_NODEFILE)"
+fi
 
 echo "--- Queue: $BUILDKITE_AGENT_META_DATA_QUEUE"
 echo "JULIA_DEPOT_PATH: $JULIA_DEPOT_PATH"
 
+# Create TMPDIR on all nodes
 case "$BUILDKITE_AGENT_META_DATA_QUEUE" in
     "new-central")
-        echo "SLURM_NODELIST: $SLURM_NODELIST"
-    
-        if ! pdsh -w $SLURM_NODELIST mkdir -p "${TMPDIR}"; then
-            echo "Warning: pdsh failed to create directory. Falling back to srun."
-            srun --ntasks-per-node=1 --ntasks=${SLURM_JOB_NUM_NODES} mkdir -p "${TMPDIR}"
-        fi
-    
-    # Check if TMPDIR was created
-        if ! srun --ntasks-per-node=1 --ntasks=${SLURM_JOB_NUM_NODES} test -d "${TMPDIR}"; then
-            echo "Error: Failed to create $TMPDIR"
-            exit 1
-        fi
         source "${SLURM_BUILDKITE_PATH}/cluster_environments/caltech_hpc.sh"
         ;;
     "clima")
+        # Clima only has one node
         mkdir -p "${TMPDIR}"
+        ;;
+    "derecho")
+        source "${SLURM_BUILDKITE_PATH}/cluster_environments/derecho.sh"
         ;;
     "test")
         mkdir -p "${TMPDIR}"
